# -*- coding: utf-8 -*-
"""Cumulative Impact Factor Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SewsqI9MbgdrVdleA-31ySBzLqKeid4n
"""

import pandas as pd

# Create a list of data
data = [
    ["Journal of Materials Science: Materials in Electronics", 3, 0.681, 4.6],
    ["IOP Conference Series: Earth and Environmental Science", 3, 0.255, 0.8],
    ["International Journal of Advanced Science and Technology", 2, 0.342, -1],
    ["Proceedings of the 4th International Conference on Devices, Circuits and Systems, ICDCS 2018", 2, 0, 0],
    ["Key Engineering Materials", 1, 0.238, 0.9],
    ["Sensors", 1, 1.317, 6.8],
    ["ECS Transactions", 1, 0.281, -1],
    ["Journal of Nanophotonics", 1, 0.503, 2.7],
    ["Nanotechnology Reviews", 1, 1.376, 9.1],
    ["Proceedings of the 2020 IEEE International Conference on Communication and Signal Processing, ICCSP", 1, 0, 0],
    ["ICPECTS 2020 - IEEE 2nd International Conference on Power, Energy, Control and Transmission Systems,", 1, 0, 0],
    ["Materials Today", 1, 3.327, 33.5],
    ["AIP Conference Proceedings", 1, 0.247, 0.7],
]

# Create a DataFrame
df = pd.DataFrame(data, columns=["Scopus Source", "Publications", "SNIP", "CiteScore 2022"])

# Replace '-' with 0
df['CiteScore 2022'].replace('-', 0, inplace=True)

# Calculate the total impact factor
total_impact_factor = df['CiteScore 2022'].sum()

# Print the total impact factor
print(total_impact_factor)